### ISSUE TITLE
Nome del file di input "hard coded"

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#12]
Il nome del file di input è scritto nel codice. 
Questo richiede una modifica del codice se si vuole leggere un altro file o anche solo se i file non è nella cartella di default.
Potreste chiedere il path del file in input all'utente, ma questo costringe a digitare il nome del file ad ongi test.
In questi casi è utile avere un path di defult che viene usato se l'utente non fornisce esplicitamente il path del file. Si può risolvere ancora chiedendolo in input e usare un default se non si digita nulla o, più elegantemente, usando i parametri da linea di comando.
Provate a rendere più generale l'uso del programma?

**Comment by CarloDiCicco** [comment]
Issue risolta nel commit del 5/02/2024 (revision number: 3059ceb1279a74d84434498c84f64da69179298d).
