### ISSUE TITLE
codice di test

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#2]
E' stata scritta una certa quantità di codice, ma c'è solo un file che consente una qualche verifica di funzionalità (testValidation.py). 

In generale è opportuno poter fare verifiche sul codice man mano che si scrive senza rimandare a quando il codice da verificare è molto consistente. Questo si può ottenere o usando le unittest, ovvero aggiungendo del codice eseguibile in ciascun file che testa il codice di quel file (proteggendo ovviamente la parte eseguibile del codice con la clausola `if __name__ == "__main__":`). 

Può anche essere utile avere fin dall'inizio un file `main.py` (o analogo) che integra tutte le funzioni in quqlche modo testabili in modo da effettuare anche test di integrazione.

**Comment by alex-thk** [comment]
E' stato aggiunto un file main.py (ex testValidation.py) vero e proprio che integra tutte le funzione al commit 365e2c5149fb394c25d70884e3c1f8ff8085d41c
Nella maggior parte dei casi è stato utilizzato il main per testare il funzionamento delle classi e delle loro funzioni
