### ISSUE TITLE
File Reader.py

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#3]
Nel commento al metodo `parse` specificare cosa viene restituito come risultato

Aggiornare analogo commento nelle clessi derivate (deve esserci lo stesso commento o, meglio un commento che reinvia al commento della classe astratta: in questo modo non bisogna mantenere duplicati)

**Comment by CarloDiCicco** [comment]
Issue risolta nel commit del 29/01/2024 (revision numer: c135d96ee9c922dd0a391396b38e567eb5b04ab6).
