### ISSUE TITLE
File Factory.py

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#4]
Il nome della classe dovrebbe far riferimento al fatto che è una factory di *reader* e non lasciare un nome generico (per es. usare una convenzione come nel caso dello splitter).

**Comment by CarloDiCicco** [comment]
Issue risolta nel commit del 29/01/2024 (revision number: a75a96fe3f9d44106a61d46f2ba1c95ba581eb1f).
