### ISSUE TITLE
File Filler.py

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#5]
Per questa classe avrebbe senso creare una unittest (non è richiesto, è solo un'idea se la ritenete utile)

**Comment by CarloDiCicco** [comment]
È stato aggiunto del codice per testare la classe "Filler" e il suo metodo "fill" protetto dalla variabile "__main__", nel commit del 2/2/2024 (revision number: 9d01b58d1af7366ce2fc869bf42c3927f34a7005).
