### ISSUE TITLE
File splitterFactory.py

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#6]
Non è ragionevole chiedere in questo punto all'utente di immetere le opzioni: vanno chieste all'inizio dell'esecuzione (o meglio ancora da da riga di comando) e passate come parametri alla factory.

`create_splitter` dovrebbe essere un metodo statico in modo che non sia necessario create un'istanza della factory per creare uno splitter.

**Comment by ValerioMontanaro** [comment]
Issue risolta nei commit del 28/01/2024

**Comment by ValerioMontanaro** [comment]
Issue risolta nel commit del 28/01/2024, 
Revision Number: 3e7384498a59604a3e7f386db3343acfd3c388e5
