### ISSUE TITLE
File knn.py

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#8]
Manca il commento su casa fa il metodo train; in particolare occorre documentare nel commento cosa rappresentano i risultati restituiti dal metodo.

Stessa cosa per il metodo test; in particolare se un metodo non restituisce nulla va documenbtato esplicitamente nel commento (in generale: leggendo interfaccia e commento deve essere possibile capire **cosa** fa un metodo o una funzione senza bisogno di leggere il codice del corpo).

Anche per questa classe (oltre a Filler) avrebbe senso creare una unittest (non è richiesto, è solo un'idea se può risultare utile).

**Comment by alex-thk** [comment]
I commenti sono stati aggiustati nel commit 38af5d268c791c751c1b4f472a3fc12c74ffd4ac -- 
Valuteremo in futuro se è necessario fare una unittest per la classe KNN.
