### ISSUE TITLE
File StratifiedCrossValidatrion.py

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#9]
Non è ragionevole chiedere in questo punto all'utente di immetere le opzioni; vanno chieste all'inizio (o meglio da riga di comando) e passate come parametri quando si crea la classe (oppure direttamente al metodo split).

**Comment by ValerioMontanaro** [comment]
Issue risolta nel commit del 28/01/2024, 
Revision Number: 7c06ed2c1bafc5e1a111394f52f9746f11503813
